### PR TITLE
Feature/mocks

### PR DESCRIPTION
**Pull request by SupremeTechnopriest**
A continuation of #22

### CODE REVIEW

**Comment by SupremeTechnopriest** [comment]
@calvinmetcalf This should have everything you requested.  Let me know if we need anything else to get this merged in.  Happy holidays! 🎄 🎁

**Comment by calvinmetcalf** [comment]
The json and html file in dist were supposed to be in there

**Comment by calvinmetcalf** [comment]
I wanna double check about process-es6 but otherwise looks pretty good, thanks for the work I'll try to get it to Monday

**Comment by SupremeTechnopriest** [comment]
My pleasure, thanks for your work on rollup.  It was tough to get here, but totally worth it.

**Comment by SupremeTechnopriest** [comment]
@calvinmetcalf Are you sure about the dist folder?  Here is your `.gitignore` on `master` https://github.com/calvinmetcalf/rollup-plugin-node-builtins/blob/master/.gitignore

**Comment by calvinmetcalf** [comment]
I manually added those even though i had them in the gitinore, but dont worry about it ill deal with it

**Comment by calvinmetcalf** [comment]
ok pushed up a few changes, not sure why process-es6 helped you as that caused errors for me

**Comment by SupremeTechnopriest** [comment]
checking to see if this still works with my set up

**Comment by SupremeTechnopriest** [comment]
@calvinmetcalf Yeah I have the same problem.  Here is a stack trace:

```
Could not resolve 'process' from /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/rollup-plugin-node-builtins/src/es6/util.js
Error: Could not resolve 'process' from /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/rollup-plugin-node-builtins/src/es6/util.js
    at Error (native)
    at /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/index.js:265:24
    at /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:14
    at process (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

So I have a library, `edgemesh-utils` that gets rolled up with format `es`.  That library is then used across 3 other projects that are rolled up for the browser with format `iife`.  It seems that `rollup-plugin-node-builtins` needs to be rolled up with its own source code as a plugin (but probably not because that would be redundant). `process` ends up being undefined in non node environments. Changing to `process-es6` made things browser compatible for me because it could resolve that library while it could not resolve `process`.

**Comment by calvinmetcalf** [comment]
did you use  rollup-plugin-node-globals as well ?

**Comment by SupremeTechnopriest** [comment]
yep here is my rollup config 

```javascript
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import builtins from 'rollup-plugin-node-builtins';
import globals from 'rollup-plugin-node-globals';
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';
import uglify from 'rollup-plugin-uglify';
import { minify } from 'uglify-js';

const isProd = process.env.NODE_ENV === 'production';
const isServer = process.env.IS_SERVER;
const file = 'edgemesh.utils';

const prodServerTargets = [{ dest: 'server/' + file + '.min.js', format: 'cjs' }];
const prodBrowserTargets = [{ dest: 'dist/' + file + '.min.js', format: 'iife' }];
const devServerTargets = [
    { dest: 'server/' + file + '.js', format: 'cjs' },
    { dest: 'server/index.js', format: 'es' }
];
const devBrowserTargets = [
    { dest: 'dist/' + file + '.browser.js', format: 'iife' },
    { dest: 'dist/' + file + '.js', format: 'es' }
];

export default {
    entry: 'src/index.js',
    moduleName: 'utils',
    plugins: [
        resolve({
            jsnext: true,
            main: true,
            browser: true,
            preferBuiltins: true
        }),
        commonjs({
            ignoreGlobal: true,
            include: 'node_modules/**',
            namedExports: {
                chai: [ 'expect', 'assert' ]
            }
        }),
        babel({
            babelrc: false,
            presets: [ 'es2015-rollup' ],
            plugins: [
                'fast-async',
                'transform-flow-strip-types',
                'transform-decorators-legacy',
                'transform-object-rest-spread',
                'transform-class-properties',
                'transform-export-extensions'
            ]
        }),
        json(),
        (!isServer && globals()),
        (!isServer && builtins()),
        (isProd && uglify({ warnings: true }, minify))
    ],
    targets: isProd
        ? ( isServer ? prodServerTargets : prodBrowserTargets )
        : ( isServer ? devServerTargets : devBrowserTargets )
};
```

**Comment by calvinmetcalf** [comment]
you need globals earlier, before resolve

**Comment by SupremeTechnopriest** [comment]
For some reason, if I dont run `babel` before `globals` I get errors compiling my code.  Example:

`rollup.config.js`
```javascript
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import builtins from 'rollup-plugin-node-builtins';
import globals from 'rollup-plugin-node-globals';
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';
import uglify from 'rollup-plugin-uglify';
import { minify } from 'uglify-js';

const isProd = process.env.NODE_ENV === 'production';
const isServer = process.env.IS_SERVER;
const file = 'edgemesh.utils';

const prodServerTargets = [{ dest: 'server/' + file + '.min.js', format: 'cjs' }];
const prodBrowserTargets = [{ dest: 'dist/' + file + '.min.js', format: 'iife' }];
const devServerTargets = [
    { dest: 'server/' + file + '.js', format: 'cjs' },
    { dest: 'server/index.js', format: 'es' }
];
const devBrowserTargets = [
    { dest: 'dist/' + file + '.browser.js', format: 'iife' },
    { dest: 'dist/' + file + '.js', format: 'es' }
];

export default {
    entry: 'src/index.js',
    moduleName: 'utils',
    plugins: [
        (!isServer && globals()),
        resolve({
            jsnext: true,
            main: true,
            browser: true,
            preferBuiltins: true
        }),
        commonjs({
            ignoreGlobal: true,
            include: 'node_modules/**',
            namedExports: {
                chai: [ 'expect', 'assert' ]
            }
        }),
        babel({
            babelrc: false,
            presets: [ 'es2015-rollup' ],
            plugins: [
                'fast-async',
                'transform-flow-strip-types',
                'transform-decorators-legacy',
                'transform-object-rest-spread',
                'transform-class-properties',
                'transform-export-extensions'
            ]
        }),
        json(),
        (!isServer && builtins()),
        (isProd && uglify({ warnings: true }, minify))
    ],
    targets: isProd
        ? ( isServer ? prodServerTargets : prodBrowserTargets )
        : ( isServer ? devServerTargets : devBrowserTargets )
};
```

`result`
```
Error transforming /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/src/mesh/index.js: Unexpected token (39:20) in /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/src/mesh/index.js
SyntaxError: Error transforming /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/src/mesh/index.js: Unexpected token (39:20) in /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/src/mesh/index.js
    at Parser.pp$4.raise (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/acorn/dist/acorn.js:2454:13)
    at Parser.pp.unexpected (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/acorn/dist/acorn.js:616:8)
    at Parser.pp.expect (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/acorn/dist/acorn.js:610:26)
    at Parser.pp$3.parseMethod (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/acorn/dist/acorn.js:2271:8)
    at Parser.pp$1.parseClassMethod (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/acorn/dist/acorn.js:1206:23)
    at Parser.pp$1.parseClass (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/acorn/dist/acorn.js:1186:12)
    at Parser.pp$3.parseExprAtom (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/acorn/dist/acorn.js:1977:17)
    at Parser.pp$3.parseExprSubscripts (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/acorn/dist/acorn.js:1854:19)
    at Parser.pp$3.parseMaybeUnary (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/acorn/dist/acorn.js:1831:17)
    at Parser.pp$3.parseExprOps (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/acorn/dist/acorn.js:1773:19)
    at Parser.pp$3.parseMaybeConditional (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/acorn/dist/acorn.js:1756:19)
    at Parser.pp$3.parseMaybeAssign (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/acorn/dist/acorn.js:1733:19)
```

In this case it's failing on the first defined class property because `transform-class-properties` hasn't been run on the code yet. 

If I move `babel` above `globals` and before resolve, I still have the same error with process being undefined. 

`rollup.config.js`
```javascript
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import builtins from 'rollup-plugin-node-builtins';
import globals from 'rollup-plugin-node-globals';
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';
import uglify from 'rollup-plugin-uglify';
import { minify } from 'uglify-js';

const isProd = process.env.NODE_ENV === 'production';
const isServer = process.env.IS_SERVER;
const file = 'edgemesh.utils';

const prodServerTargets = [{ dest: 'server/' + file + '.min.js', format: 'cjs' }];
const prodBrowserTargets = [{ dest: 'dist/' + file + '.min.js', format: 'iife' }];
const devServerTargets = [
    { dest: 'server/' + file + '.js', format: 'cjs' },
    { dest: 'server/index.js', format: 'es' }
];
const devBrowserTargets = [
    { dest: 'dist/' + file + '.browser.js', format: 'iife' },
    { dest: 'dist/' + file + '.js', format: 'es' }
];

export default {
    entry: 'src/index.js',
    moduleName: 'utils',
    plugins: [
        babel({
            babelrc: false,
            presets: [ 'es2015-rollup' ],
            plugins: [
                'fast-async',
                'transform-flow-strip-types',
                'transform-decorators-legacy',
                'transform-object-rest-spread',
                'transform-class-properties',
                'transform-export-extensions'
            ]
        }),
        (!isServer && globals()),
        resolve({
            jsnext: true,
            main: true,
            browser: true,
            preferBuiltins: true
        }),
        commonjs({
            ignoreGlobal: true,
            include: 'node_modules/**',
            namedExports: {
                chai: [ 'expect', 'assert' ]
            }
        }),
        json(),
        (!isServer && builtins()),
        (isProd && uglify({ warnings: true }, minify))
    ],
    targets: isProd
        ? ( isServer ? prodServerTargets : prodBrowserTargets )
        : ( isServer ? devServerTargets : devBrowserTargets )
};
```

`result`
```
Could not resolve 'process' from /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/rollup-plugin-node-builtins/src/es6/util.js
Error: Could not resolve 'process' from /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/rollup-plugin-node-builtins/src/es6/util.js
    at Error (native)
    at /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/index.js:265:24
    at /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:14
    at process (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/rl/Sites/clients/edgemesh/edgemesh/edgemesh-utils/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by calvinmetcalf** [comment]
Put globals and builtins before resolve and after Babel

**Comment by SupremeTechnopriest** [comment]
that results in:

```
'default' is not exported by node_modules/array-keys/index.js (imported by src/coms/index.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
```

which is solved by resolve.

Maybe `globals` `builtins` and `resolve` should be rolled into one plugin?  I haven't done too much looking under the hood of rollup, but seems to be some kind of race condition between plugins.

**Comment by calvinmetcalf** [comment]
There is some long term talk of combining globals with cjs and builtins
with resolve, I'm on vacation rest of this week but can look into it next
week, in the meantime the cjs config module is something I threw together a
while back to get all the config in the right order

On Tue, Dec 27, 2016, 1:49 AM Randy Lebeau <notifications@github.com> wrote:

that results in:

'default' is not exported by node_modules/array-keys/index.js
(imported by src/coms/index.js). For help fixing this error see
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

which is solved by resolve.

Maybe globals builtins and resolve should be rolled into one plugin? I
haven't done too much looking under the hood of rollup, but seems to be
some kind of race condition between plugins.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/calvinmetcalf/rollup-plugin-node-builtins/pull/23#issuecomment-269252607>,
or mute the thread

**Comment by calvinmetcalf** [comment]
I'm back from vacation will take a look in the next day or 2

**Comment by SupremeTechnopriest** [comment]
Sounds good let me know how I can help.  Im currently working on getting a [webworkify](https://github.com/substack/webworkify) rollup equivalent together.

**Comment by calvinmetcalf** [comment]
re webworkify you may be better off just creating a second bundle and pointing to it separately, I'm not sure how much easier doing object url style hacks are going to make it long term

**Comment by SupremeTechnopriest** [comment]
👋  @calvinmetcalf @rich-harris 

I took a stab at combining `rollup-plugin-node-resolve` and `rollup-plugin-node-builtins`.  I was getting some weird issues trying to rollup my project which admittedly has a very complex build chain.  I also added a few more options:

### `browserModule`
Add the `browserModule` property to `package.json` and set this to true to prefer browser built `es` over `module`.  I needed this to get my isomorphic library to work with rollup. 

### `moduleDirectory`
Allows for usage of custom resolve paths with node-resolve.  Same as setting `NODE_PATH` env.  `node_modules` gets concatenated so you only have to add your custom library.  In my case it was
```javascript
{
    moduleDirectory: [ 'src' ]
}
```

### `preferBuiltins`
Setting `preferBuiltins` to `true` will use browser ready es6 versions of node builtins where applicable.  

### `builtins`
The heavier libraries are still configurable. `fs` and `crypto` will resolve empty by default but can be configured to load browser replacements with the `builtins` function.
```javascript
{
   builtins: {
        fs: true,
        crypto: true
}
```

## Pull Request

The library is located [here](https://github.com/SupremeTechnopriest/rollup-plugin-node-resolve).  I haven't submitted a PR because I'm not sure if this is something you are interested in doing.  If you would like me to submit a PR I will.  Otherwise I will maintain my own project as these changes are required to build my project. 

Thanks for your work on Rollup.  While it was extremely frustrating for me to get up and running, it was most certainly worth the effort.  Builds so fast!

**Comment by calvinmetcalf** [comment]
tot's forgot about this, thanks merged can publish latter today

**Pull request merged**
